register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api_login_check:
    path: /api/login_check
    methods: [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

